// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: ride_data.proto

package grpc_poc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents an individual ride data record
type RideData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key              string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	FareAmount       string `protobuf:"bytes,2,opt,name=fare_amount,json=fareAmount,proto3" json:"fare_amount,omitempty"`
	PickupDatetime   string `protobuf:"bytes,3,opt,name=pickup_datetime,json=pickupDatetime,proto3" json:"pickup_datetime,omitempty"`
	PickupLongitude  string `protobuf:"bytes,4,opt,name=pickup_longitude,json=pickupLongitude,proto3" json:"pickup_longitude,omitempty"`
	PickupLatitude   string `protobuf:"bytes,5,opt,name=pickup_latitude,json=pickupLatitude,proto3" json:"pickup_latitude,omitempty"`
	DropoffLongitude string `protobuf:"bytes,6,opt,name=dropoff_longitude,json=dropoffLongitude,proto3" json:"dropoff_longitude,omitempty"`
	DropoffLatitude  string `protobuf:"bytes,7,opt,name=dropoff_latitude,json=dropoffLatitude,proto3" json:"dropoff_latitude,omitempty"`
	PassengerCount   string `protobuf:"bytes,8,opt,name=passenger_count,json=passengerCount,proto3" json:"passenger_count,omitempty"`
}

func (x *RideData) Reset() {
	*x = RideData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ride_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideData) ProtoMessage() {}

func (x *RideData) ProtoReflect() protoreflect.Message {
	mi := &file_ride_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideData.ProtoReflect.Descriptor instead.
func (*RideData) Descriptor() ([]byte, []int) {
	return file_ride_data_proto_rawDescGZIP(), []int{0}
}

func (x *RideData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RideData) GetFareAmount() string {
	if x != nil {
		return x.FareAmount
	}
	return ""
}

func (x *RideData) GetPickupDatetime() string {
	if x != nil {
		return x.PickupDatetime
	}
	return ""
}

func (x *RideData) GetPickupLongitude() string {
	if x != nil {
		return x.PickupLongitude
	}
	return ""
}

func (x *RideData) GetPickupLatitude() string {
	if x != nil {
		return x.PickupLatitude
	}
	return ""
}

func (x *RideData) GetDropoffLongitude() string {
	if x != nil {
		return x.DropoffLongitude
	}
	return ""
}

func (x *RideData) GetDropoffLatitude() string {
	if x != nil {
		return x.DropoffLatitude
	}
	return ""
}

func (x *RideData) GetPassengerCount() string {
	if x != nil {
		return x.PassengerCount
	}
	return ""
}

// Represents a chunk of ride data (an array of RideData objects)
type CreateRideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedRides []*RideData `protobuf:"bytes,1,rep,name=created_rides,json=createdRides,proto3" json:"created_rides,omitempty"`
}

func (x *CreateRideResponse) Reset() {
	*x = CreateRideResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ride_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideResponse) ProtoMessage() {}

func (x *CreateRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ride_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideResponse.ProtoReflect.Descriptor instead.
func (*CreateRideResponse) Descriptor() ([]byte, []int) {
	return file_ride_data_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRideResponse) GetCreatedRides() []*RideData {
	if x != nil {
		return x.CreatedRides
	}
	return nil
}

// CreateRideRequest can be used to request ride data (empty here if not needed)
type CreateRideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateRideRequest) Reset() {
	*x = CreateRideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ride_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideRequest) ProtoMessage() {}

func (x *CreateRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ride_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideRequest.ProtoReflect.Descriptor instead.
func (*CreateRideRequest) Descriptor() ([]byte, []int) {
	return file_ride_data_proto_rawDescGZIP(), []int{2}
}

var File_ride_data_proto protoreflect.FileDescriptor

var file_ride_data_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x69, 0x64, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xbb, 0x02, 0x0a, 0x08, 0x52, 0x69, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x61, 0x72, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x61, 0x72, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x69, 0x63, 0x6b,
	0x75, 0x70, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x69,
	0x63, 0x6b, 0x75, 0x70, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x4c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x5f,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x2b,
	0x0a, 0x11, 0x64, 0x72, 0x6f, 0x70, 0x6f, 0x66, 0x66, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x64, 0x72, 0x6f, 0x70, 0x6f,
	0x66, 0x66, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x64,
	0x72, 0x6f, 0x70, 0x6f, 0x66, 0x66, 0x5f, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x72, 0x6f, 0x70, 0x6f, 0x66, 0x66, 0x4c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e,
	0x67, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x44, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x72, 0x69, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52,
	0x69, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x52, 0x69, 0x64, 0x65, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x3b, 0x0a, 0x04, 0x52, 0x69,
	0x64, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x61, 0x74, 0x68, 0x69, 0x72, 0x76, 0x65, 0x6c, 0x43,
	0x68, 0x61, 0x6e, 0x64, 0x72, 0x61, 0x73, 0x65, 0x6b, 0x61, 0x72, 0x61, 0x6e, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x70, 0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ride_data_proto_rawDescOnce sync.Once
	file_ride_data_proto_rawDescData = file_ride_data_proto_rawDesc
)

func file_ride_data_proto_rawDescGZIP() []byte {
	file_ride_data_proto_rawDescOnce.Do(func() {
		file_ride_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_ride_data_proto_rawDescData)
	})
	return file_ride_data_proto_rawDescData
}

var file_ride_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ride_data_proto_goTypes = []any{
	(*RideData)(nil),           // 0: RideData
	(*CreateRideResponse)(nil), // 1: CreateRideResponse
	(*CreateRideRequest)(nil),  // 2: CreateRideRequest
}
var file_ride_data_proto_depIdxs = []int32{
	0, // 0: CreateRideResponse.created_rides:type_name -> RideData
	2, // 1: Ride.Create:input_type -> CreateRideRequest
	1, // 2: Ride.Create:output_type -> CreateRideResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ride_data_proto_init() }
func file_ride_data_proto_init() {
	if File_ride_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ride_data_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RideData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ride_data_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRideResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ride_data_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ride_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ride_data_proto_goTypes,
		DependencyIndexes: file_ride_data_proto_depIdxs,
		MessageInfos:      file_ride_data_proto_msgTypes,
	}.Build()
	File_ride_data_proto = out.File
	file_ride_data_proto_rawDesc = nil
	file_ride_data_proto_goTypes = nil
	file_ride_data_proto_depIdxs = nil
}
