// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: ride_data.proto

package grpc_poc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ride_Create_FullMethodName = "/Ride/Create"
)

// RideClient is the client API for Ride service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RideClient interface {
	Create(ctx context.Context, in *CreateRideRequest, opts ...grpc.CallOption) (*CreateRideResponse, error)
}

type rideClient struct {
	cc grpc.ClientConnInterface
}

func NewRideClient(cc grpc.ClientConnInterface) RideClient {
	return &rideClient{cc}
}

func (c *rideClient) Create(ctx context.Context, in *CreateRideRequest, opts ...grpc.CallOption) (*CreateRideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRideResponse)
	err := c.cc.Invoke(ctx, Ride_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RideServer is the server API for Ride service.
// All implementations must embed UnimplementedRideServer
// for forward compatibility.
type RideServer interface {
	Create(context.Context, *CreateRideRequest) (*CreateRideResponse, error)
	mustEmbedUnimplementedRideServer()
}

// UnimplementedRideServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRideServer struct{}

func (UnimplementedRideServer) Create(context.Context, *CreateRideRequest) (*CreateRideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRideServer) mustEmbedUnimplementedRideServer() {}
func (UnimplementedRideServer) testEmbeddedByValue()              {}

// UnsafeRideServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RideServer will
// result in compilation errors.
type UnsafeRideServer interface {
	mustEmbedUnimplementedRideServer()
}

func RegisterRideServer(s grpc.ServiceRegistrar, srv RideServer) {
	// If the following call pancis, it indicates UnimplementedRideServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ride_ServiceDesc, srv)
}

func _Ride_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ride_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServer).Create(ctx, req.(*CreateRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ride_ServiceDesc is the grpc.ServiceDesc for Ride service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ride_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Ride",
	HandlerType: (*RideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Ride_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ride_data.proto",
}
